strict_chain
proxy_dns
# Change this to 224 if you want, but ensure proxy_dns is uncommented
remote_dns_subnet 224
tcp_read_time_out 15000
tcp_connect_time_out 8000

[ProxyList]
# Force IPv4 explicitly
socks5 127.0.0.1 9999
