base{
    daemon = off;
    log_debug = off;
    log_info = on;
    redirector = iptables;
}
redsocks {
    local_ip = 0.0.0.0;
    local_port = 12345;
    ip = host.docker.internal;
    port = 9999;
    type = socks5;
}
